
name: Build UF2 Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Important if your project has submodules

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: Create build directory
      run: mkdir build && cd build && cmake ..

    - name: Build project
      run: cd build && make -j4

    - name: Check for UF2 file
      run: |
        cd build
        if [ -f *.uf2 ]; then
          echo "UF2 file found"
          ls -lh *.uf2
        else
          echo "No UF2 file found"
          exit 1
        fi

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: build/*.uf2
