name: ZMK Firmware Build

on:
  # Kích hoạt khi push code vào nhánh main
  push:
    branches: [ main ]
    paths:
      - 'config/**'  # Chỉ chạy khi file trong thư mục config thay đổi
      
  # Kích hoạt khi tạo pull request
  pull_request:
    paths:
      - 'config/**'
      
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-latest  # Máy ảo Ubuntu để build
    
    steps:
      # Bước 1: Checkout code (bao gồm cả submodule ZMK)
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Quan trọng: để clone cả ZMK submodule
          
      # Bước 2: Build firmware bằng action chính thức của ZMK
      - name: Build ZMK Firmware
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
        with:
          config_path: 'config'  # Thư mục chứa cấu hình
          build_matrix_path: 'config/builds.yaml'  # File định nghĩa các bản build
          archive_name: 'zmk-firmware'  # Tên file zip đầu ra
          
      # Bước 3: Upload firmware dưới dạng artifact
      - name: Upload Firmware
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            firmware/*.uf2
            firmware/*.bin
          retention-days: 7  # Tự động xóa sau 7 ngày
