
on: 
  push: 
    paths: 
      - 'config/**'
  pull_request: 
    paths: 
      - 'config/**'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Firmware
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake \
            ninja-build \
            gcc \
            gcc-multilib \
            g++-multilib \
            libc6-dev \
            libtool \
            automake \
            autoconf \
            dfu-util \
            wget

      - name: Build firmware
        run: |
          cd config
          python3 ../build.py
          
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: pipar-firmware
          path: config/build/*.uf2
